-- Sentinel OSS data foundation. Run as SYSADMIN after creating the database/warehouses.
CREATE DATABASE IF NOT EXISTS SUPPLY_CHAIN_MONITOR;
CREATE SCHEMA IF NOT EXISTS SUPPLY_CHAIN_MONITOR.DETECTION;
USE SCHEMA SUPPLY_CHAIN_MONITOR.DETECTION;

CREATE TABLE IF NOT EXISTS INGESTION_CHECKPOINTS (
  SOURCE_KEY STRING NOT NULL,
  STATUS STRING NOT NULL,
  ROW_COUNT NUMBER DEFAULT 0,
  COMPLETED_AT TIMESTAMP_TZ,
  ERROR_MESSAGE STRING,
  UPDATED_AT TIMESTAMP_TZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS GHARCHIVE_EVENTS_HOURLY (
  EVENT_ID STRING NOT NULL,
  EVENT_CREATED_AT TIMESTAMP_TZ NOT NULL,
  EVENT_TYPE STRING NOT NULL,
  ACTOR_LOGIN STRING,
  ACTOR_ID NUMBER,
  REPO_NAME STRING,
  REPO_ID NUMBER,
  ORG_LOGIN STRING,
  PAYLOAD VARIANT,
  ACTION STRING,
  REF STRING,
  REF_TYPE STRING,
  PUSH_ID NUMBER,
  HEAD STRING,
  BEFORE STRING,
  SIZE NUMBER,
  DISTINCT_SIZE NUMBER,
  MEMBER_LOGIN STRING,
  MEMBER_ID NUMBER,
  SOURCE_FILE STRING,
  INGESTED_AT TIMESTAMP_TZ DEFAULT CURRENT_TIMESTAMP()
)
CLUSTER BY (TO_DATE(EVENT_CREATED_AT), EVENT_TYPE, REPO_NAME);

CREATE TRANSIENT TABLE IF NOT EXISTS GHARCHIVE_EVENTS_BUFFER
  LIKE GHARCHIVE_EVENTS_HOURLY;

CREATE TABLE IF NOT EXISTS SECURITY_ADVISORIES (
  SOURCE STRING NOT NULL,
  ADVISORY_ID STRING NOT NULL,
  GHSA_ID STRING,
  CVE_ID STRING,
  SEVERITY STRING,
  SUMMARY STRING,
  DESCRIPTION STRING,
  PUBLISHED_AT TIMESTAMP_TZ,
  UPDATED_AT TIMESTAMP_TZ,
  WITHDRAWN_AT TIMESTAMP_TZ,
  RAW VARIANT,
  INGESTED_AT TIMESTAMP_TZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS ADVISORY_AFFECTED_PACKAGES (
  SOURCE STRING NOT NULL,
  ADVISORY_ID STRING NOT NULL,
  ECOSYSTEM STRING,
  PACKAGE_NAME STRING,
  VULNERABLE_RANGE STRING,
  FIRST_PATCHED_VERSION STRING,
  RAW VARIANT,
  INGESTED_AT TIMESTAMP_TZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS REPOSITORY_DEPENDENCIES (
  REPO_NAME STRING NOT NULL,
  PACKAGE_NAME STRING NOT NULL,
  RESOLVED_VERSION STRING,
  PURL STRING,
  SPDX_ID STRING,
  OBSERVED_AT TIMESTAMP_TZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS REPOSITORY_DEPENDENCY_EXPOSURES (
  REPO_NAME STRING NOT NULL,
  PACKAGE_NAME STRING NOT NULL,
  RESOLVED_VERSION STRING,
  ECOSYSTEM STRING,
  ADVISORY_SOURCE STRING,
  ADVISORY_ID STRING,
  SEVERITY STRING,
  MATCH_STATUS STRING,
  MATCH_REASON STRING,
  COMPUTED_AT TIMESTAMP_TZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS RISK_SCORES (
  RISK_ID STRING NOT NULL,
  REPO_NAME STRING NOT NULL,
  ACTOR_LOGIN STRING,
  COMPOSITE_SCORE FLOAT NOT NULL,
  RISK_LEVEL STRING NOT NULL,
  SIGNALS_FIRED ARRAY,
  AI_EXPLANATION STRING,
  LATEST_ACTIVITY TIMESTAMP_TZ,
  DATA_SOURCES ARRAY,
  SIGNAL_DETAILS VARIANT,
  COMPUTED_AT TIMESTAMP_TZ DEFAULT CURRENT_TIMESTAMP()
);
