USE SCHEMA SUPPLY_CHAIN_MONITOR.DETECTION;

CREATE OR REPLACE VIEW SIGNAL_NEW_COLLAB_FAST_PUSH AS
WITH additions AS (
  SELECT EVENT_ID, EVENT_CREATED_AT, REPO_NAME, MEMBER_LOGIN
  FROM GHARCHIVE_EVENTS_HOURLY
  WHERE EVENT_TYPE='MemberEvent' AND ACTION='added' AND MEMBER_LOGIN IS NOT NULL
), pushes AS (
  SELECT EVENT_ID, EVENT_CREATED_AT, REPO_NAME, ACTOR_LOGIN
  FROM GHARCHIVE_EVENTS_HOURLY
  WHERE EVENT_TYPE='PushEvent'
), matches AS (
  SELECT p.EVENT_ID PUSH_EVENT_ID, a.EVENT_ID MEMBER_EVENT_ID, p.REPO_NAME, p.ACTOR_LOGIN,
         p.EVENT_CREATED_AT OBSERVED_AT,
         DATEDIFF('minute', a.EVENT_CREATED_AT, p.EVENT_CREATED_AT) MINUTES_TO_PUSH,
         ROW_NUMBER() OVER (
           PARTITION BY p.EVENT_ID ORDER BY a.EVENT_CREATED_AT DESC
         ) AS RN
  FROM pushes p JOIN additions a
    ON p.REPO_NAME=a.REPO_NAME AND p.ACTOR_LOGIN=a.MEMBER_LOGIN
   AND p.EVENT_CREATED_AT BETWEEN a.EVENT_CREATED_AT AND DATEADD('hour', 24, a.EVENT_CREATED_AT)
)
SELECT 'new_collaborator_fast_push' SIGNAL_NAME,
       LEAST(95, 55 + 40 * EXP(-MINUTES_TO_PUSH / 180.0)) SCORE,
       REPO_NAME, ACTOR_LOGIN, OBSERVED_AT,
       'Push occurred ' || MINUTES_TO_PUSH || ' minutes after access was added.' EVIDENCE,
       ARRAY_CONSTRUCT(MEMBER_EVENT_ID, PUSH_EVENT_ID) EVENT_IDS
FROM matches WHERE RN=1;

CREATE OR REPLACE VIEW SIGNAL_MULTI_REPO_BURST AS
WITH pushes AS (
  SELECT EVENT_ID, EVENT_CREATED_AT, ACTOR_LOGIN, REPO_NAME
  FROM GHARCHIVE_EVENTS_HOURLY
  WHERE EVENT_TYPE='PushEvent' AND ACTOR_LOGIN IS NOT NULL
    AND EVENT_CREATED_AT >= DATEADD('day', -30, CURRENT_TIMESTAMP())
), bursts AS (
  SELECT anchor.ACTOR_LOGIN, anchor.EVENT_CREATED_AT OBSERVED_AT,
         COUNT(DISTINCT candidate.REPO_NAME) REPO_COUNT,
         ARRAY_AGG(DISTINCT candidate.EVENT_ID) EVENT_IDS,
         ARRAY_AGG(DISTINCT candidate.REPO_NAME) REPOS
  FROM pushes anchor JOIN pushes candidate
    ON anchor.ACTOR_LOGIN=candidate.ACTOR_LOGIN
   AND candidate.EVENT_CREATED_AT BETWEEN DATEADD('hour',-1,anchor.EVENT_CREATED_AT)
                                      AND anchor.EVENT_CREATED_AT
  GROUP BY anchor.ACTOR_LOGIN, anchor.EVENT_ID, anchor.EVENT_CREATED_AT
  HAVING COUNT(DISTINCT candidate.REPO_NAME) >= 10
  QUALIFY ROW_NUMBER() OVER (
    PARTITION BY anchor.ACTOR_LOGIN, DATE_TRUNC('hour',anchor.EVENT_CREATED_AT)
    ORDER BY REPO_COUNT DESC, anchor.EVENT_CREATED_AT
  )=1
)
SELECT 'multi_repo_burst' SIGNAL_NAME, LEAST(98, 70 + (REPO_COUNT-10)*3) SCORE,
       REPOS[0]::STRING REPO_NAME, ACTOR_LOGIN, OBSERVED_AT,
       'Actor pushed to ' || REPO_COUNT || ' repositories within one hour.' EVIDENCE,
       EVENT_IDS
FROM bursts;

CREATE OR REPLACE VIEW SIGNAL_SUSPICIOUS_COMMIT_MESSAGES AS
WITH messages AS (
  SELECT e.EVENT_ID, e.EVENT_CREATED_AT, e.REPO_NAME, e.ACTOR_LOGIN,
         c.value:message::STRING MESSAGE
  FROM GHARCHIVE_EVENTS_HOURLY e,
       LATERAL FLATTEN(INPUT => e.PAYLOAD:commits, OUTER => FALSE) c
  WHERE e.EVENT_TYPE='PushEvent'
), matched AS (
  SELECT *,
    REGEXP_LIKE(MESSAGE, '(preinstall|postinstall|prepare|setup\\.py|install script)', 'i') INSTALL_HOOK,
    REGEXP_LIKE(MESSAGE, '(eval\\s*\\(|fromcharcode|base64|atob\\s*\\(|obfuscat|encoded payload)', 'i') OBFUSCATION,
    REGEXP_LIKE(MESSAGE, '(token|credential|secret|\\.npmrc|aws_access_key|github_token)', 'i') CREDENTIAL_ACCESS,
    REGEXP_LIKE(MESSAGE, '(curl|wget|invoke-webrequest).*(sh|bash|powershell|iex)', 'i') DOWNLOAD_EXECUTE
  FROM messages
)
SELECT 'suspicious_commit_message' SIGNAL_NAME,
       LEAST(72, GREATEST(IFF(INSTALL_HOOK,42,0), IFF(OBFUSCATION,58,0),
              IFF(CREDENTIAL_ACCESS,54,0), IFF(DOWNLOAD_EXECUTE,70,0))) SCORE,
       REPO_NAME, ACTOR_LOGIN, EVENT_CREATED_AT OBSERVED_AT,
       'Commit metadata matched a suspicious behavior pattern; review the actual diff.' EVIDENCE,
       ARRAY_CONSTRUCT(EVENT_ID) EVENT_IDS
FROM matched WHERE INSTALL_HOOK OR OBFUSCATION OR CREDENTIAL_ACCESS OR DOWNLOAD_EXECUTE;

CREATE OR REPLACE VIEW SIGNAL_DEPENDENCY_EXPOSURE AS
SELECT 'dependency_exposure' SIGNAL_NAME,
       CASE LOWER(SEVERITY) WHEN 'critical' THEN 92 WHEN 'high' THEN 76
            WHEN 'medium' THEN 52 ELSE 35 END SCORE,
       REPO_NAME, NULL ACTOR_LOGIN, MAX(COMPUTED_AT) OBSERVED_AT,
       'Resolved ' || PACKAGE_NAME || '@' || COALESCE(RESOLVED_VERSION,'unknown') ||
       ' is affected by ' || ADVISORY_ID || '.' EVIDENCE,
       ARRAY_CONSTRUCT(ADVISORY_ID) EVENT_IDS
FROM REPOSITORY_DEPENDENCY_EXPOSURES
WHERE MATCH_STATUS='confirmed_vulnerable'
GROUP BY REPO_NAME, PACKAGE_NAME, RESOLVED_VERSION, ADVISORY_ID, SEVERITY;

CREATE OR REPLACE PROCEDURE REFRESH_RISK_SCORES()
RETURNS STRING
LANGUAGE SQL
AS
$$
BEGIN
  TRUNCATE TABLE RISK_SCORES;
  INSERT INTO RISK_SCORES (
    RISK_ID, REPO_NAME, ACTOR_LOGIN, COMPOSITE_SCORE, RISK_LEVEL,
    SIGNALS_FIRED, AI_EXPLANATION, LATEST_ACTIVITY, DATA_SOURCES, SIGNAL_DETAILS
  )
  WITH all_signals AS (
    SELECT * FROM SIGNAL_NEW_COLLAB_FAST_PUSH
    UNION ALL SELECT * FROM SIGNAL_MULTI_REPO_BURST
    UNION ALL SELECT * FROM SIGNAL_SUSPICIOUS_COMMIT_MESSAGES
    UNION ALL SELECT * FROM SIGNAL_DEPENDENCY_EXPOSURE
  ), grouped AS (
    SELECT REPO_NAME, ACTOR_LOGIN, MAX(OBSERVED_AT) LATEST_ACTIVITY,
           ARRAY_AGG(DISTINCT SIGNAL_NAME) SIGNALS_FIRED,
           ARRAY_AGG(OBJECT_CONSTRUCT('name',SIGNAL_NAME,'score',SCORE,'evidence',EVIDENCE)) DETAILS,
           100 * (1 - EXP(SUM(LN(GREATEST(0.001, 1-SCORE/100))))) COMPOSITE_SCORE
    FROM all_signals
    WHERE OBSERVED_AT >= DATEADD('day', -30, CURRENT_TIMESTAMP())
    GROUP BY REPO_NAME, ACTOR_LOGIN
  )
  SELECT UUID_STRING(), REPO_NAME, ACTOR_LOGIN, LEAST(100, ROUND(COMPOSITE_SCORE,1)),
         CASE WHEN COMPOSITE_SCORE>=85 THEN 'CRITICAL' WHEN COMPOSITE_SCORE>=65 THEN 'HIGH'
              WHEN COMPOSITE_SCORE>=40 THEN 'MEDIUM' ELSE 'LOW' END,
         SIGNALS_FIRED,
         'Behavioral and dependency signals require maintainer review; commit-message matches do not inspect diffs.',
         LATEST_ACTIVITY, ARRAY_CONSTRUCT('gharchive_hourly','github_advisories','osv'),
         OBJECT_CONSTRUCT('signals', DETAILS)
  FROM grouped;
  RETURN 'ok';
END;
$$;

CREATE OR REPLACE PROCEDURE CHECK_REPO_RISK(REPO STRING, WINDOW_START DATE, WINDOW_END DATE)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
DECLARE RESULT VARIANT;
BEGIN
  SELECT OBJECT_CONSTRUCT(
    'repo', :REPO,
    'composite_score', COALESCE(MAX(COMPOSITE_SCORE),0),
    'risk_level', LOWER(COALESCE(MAX_BY(RISK_LEVEL,COMPOSITE_SCORE),'LOW')),
    'signals', COALESCE(MAX_BY(SIGNAL_DETAILS,COMPOSITE_SCORE),OBJECT_CONSTRUCT()),
    'ai_explanation', MAX(AI_EXPLANATION),
    'blast_radius_repos', ARRAY_CONSTRUCT(),
    'dependency_exposures', COALESCE((
      SELECT ARRAY_AGG(OBJECT_CONSTRUCT(
        'ecosystem',ECOSYSTEM,'package_name',PACKAGE_NAME,'resolved_version',RESOLVED_VERSION,
        'advisory_source',ADVISORY_SOURCE,'advisory_id',ADVISORY_ID,
        'advisory_type','reviewed','severity',SEVERITY,'match_status',MATCH_STATUS,
        'match_reason',MATCH_REASON
      )) FROM REPOSITORY_DEPENDENCY_EXPOSURES WHERE REPO_NAME=:REPO
    ),ARRAY_CONSTRUCT()),
    'window_start', TO_VARCHAR(:WINDOW_START),
    'window_end', TO_VARCHAR(:WINDOW_END),
    'data_sources', ARRAY_CONSTRUCT('gharchive_hourly','github_advisories','osv'),
    'computed_at', TO_VARCHAR(CURRENT_TIMESTAMP())
  ) INTO :RESULT
  FROM RISK_SCORES
  WHERE REPO_NAME=:REPO AND LATEST_ACTIVITY::DATE BETWEEN :WINDOW_START AND :WINDOW_END;
  RETURN RESULT;
END;
$$;

CREATE OR REPLACE PROCEDURE GET_DASHBOARD_OVERVIEW(WINDOW_START TIMESTAMP_TZ, WINDOW_END TIMESTAMP_TZ)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
DECLARE RESULT VARIANT;
BEGIN
  SELECT OBJECT_CONSTRUCT(
    'metrics', ARRAY_CONSTRUCT(
      OBJECT_CONSTRUCT('label','Critical findings','value',COUNT_IF(RISK_LEVEL='CRITICAL'),'delta',0,'note','selected window'),
      OBJECT_CONSTRUCT('label','Repos monitored','value',COUNT(DISTINCT REPO_NAME),'delta',0,'note','selected window'),
      OBJECT_CONSTRUCT('label','Exposed packages','value',(SELECT COUNT(*) FROM REPOSITORY_DEPENDENCY_EXPOSURES WHERE MATCH_STATUS='confirmed_vulnerable'),'delta',0,'note','confirmed'),
      OBJECT_CONSTRUCT('label','Active actors','value',COUNT(DISTINCT ACTOR_LOGIN),'delta',0,'note','flagged')
    ),
    'trend', COALESCE((
      SELECT ARRAY_AGG(OBJECT_CONSTRUCT('timestamp',TO_VARCHAR(HOUR),'score',SCORE))
             WITHIN GROUP (ORDER BY HOUR)
      FROM (
        SELECT DATE_TRUNC('hour',LATEST_ACTIVITY) HOUR,
               LEAST(100,MAX(COMPOSITE_SCORE)) SCORE
        FROM RISK_SCORES
        WHERE LATEST_ACTIVITY BETWEEN :WINDOW_START AND :WINDOW_END
        GROUP BY HOUR
      )
    ),ARRAY_CONSTRUCT()),
    'signal_distribution', COALESCE((
      SELECT ARRAY_AGG(OBJECT_CONSTRUCT('signal',SIGNAL,'percentage',PERCENTAGE))
             WITHIN GROUP (ORDER BY PERCENTAGE DESC)
      FROM (
        SELECT f.value::STRING SIGNAL,
               ROUND(100*COUNT(*)/NULLIF(SUM(COUNT(*)) OVER (),0),1) PERCENTAGE
        FROM RISK_SCORES r, LATERAL FLATTEN(INPUT=>r.SIGNALS_FIRED) f
        WHERE r.LATEST_ACTIVITY BETWEEN :WINDOW_START AND :WINDOW_END
        GROUP BY SIGNAL
      )
    ),ARRAY_CONSTRUCT()),
    'pipeline', ARRAY_CONSTRUCT(
      OBJECT_CONSTRUCT_KEEP_NULL('source','gharchive','last_success_at',(
        SELECT TO_VARCHAR(MAX(COMPLETED_AT)) FROM INGESTION_CHECKPOINTS
        WHERE SOURCE_KEY LIKE 'gharchive:%'
      ),'cadence','hourly','status',IFF((
        SELECT MAX(COMPLETED_AT) FROM INGESTION_CHECKPOINTS
        WHERE SOURCE_KEY LIKE 'gharchive:%'
      )>=DATEADD('hour',-3,CURRENT_TIMESTAMP()),'healthy','delayed')),
      OBJECT_CONSTRUCT_KEEP_NULL('source','github_advisories','last_success_at',(
        SELECT TO_VARCHAR(MAX(COMPLETED_AT)) FROM INGESTION_CHECKPOINTS
        WHERE SOURCE_KEY='github_advisories'
      ),'cadence','daily','status','healthy'),
      OBJECT_CONSTRUCT_KEEP_NULL('source','osv','last_success_at',(
        SELECT TO_VARCHAR(MAX(COMPLETED_AT)) FROM INGESTION_CHECKPOINTS
        WHERE SOURCE_KEY='osv_queries'
      ),'cadence','daily','status','healthy')
    ),
    'generated_at', TO_VARCHAR(CURRENT_TIMESTAMP())
  ) INTO :RESULT
  FROM RISK_SCORES WHERE LATEST_ACTIVITY BETWEEN :WINDOW_START AND :WINDOW_END;
  RETURN RESULT;
END;
$$;
