USE ROLE SECURITYADMIN;
CREATE ROLE IF NOT EXISTS DASHBOARD_ROLE;
CREATE ROLE IF NOT EXISTS INGESTION_ROLE;

USE ROLE SYSADMIN;
CREATE WAREHOUSE IF NOT EXISTS HACKATHON_WH WAREHOUSE_SIZE='XSMALL' AUTO_SUSPEND=60 AUTO_RESUME=TRUE;
CREATE WAREHOUSE IF NOT EXISTS INGEST_WH WAREHOUSE_SIZE='XSMALL' AUTO_SUSPEND=60 AUTO_RESUME=TRUE;

USE ROLE SECURITYADMIN;
CREATE USER IF NOT EXISTS DASHBOARD_SVC
  TYPE=SERVICE DEFAULT_ROLE=DASHBOARD_ROLE DEFAULT_WAREHOUSE=HACKATHON_WH
  COMMENT='Sentinel OSS read-only API user';
CREATE USER IF NOT EXISTS INGESTION_SVC
  TYPE=SERVICE DEFAULT_ROLE=INGESTION_ROLE DEFAULT_WAREHOUSE=INGEST_WH
  COMMENT='Sentinel OSS scheduled ingestion user';
GRANT ROLE DASHBOARD_ROLE TO USER DASHBOARD_SVC;
GRANT ROLE INGESTION_ROLE TO USER INGESTION_SVC;

GRANT USAGE ON WAREHOUSE HACKATHON_WH TO ROLE DASHBOARD_ROLE;
GRANT USAGE ON WAREHOUSE INGEST_WH TO ROLE INGESTION_ROLE;
GRANT USAGE ON DATABASE SUPPLY_CHAIN_MONITOR TO ROLE DASHBOARD_ROLE;
GRANT USAGE ON DATABASE SUPPLY_CHAIN_MONITOR TO ROLE INGESTION_ROLE;
GRANT USAGE ON SCHEMA SUPPLY_CHAIN_MONITOR.DETECTION TO ROLE DASHBOARD_ROLE;
GRANT USAGE ON SCHEMA SUPPLY_CHAIN_MONITOR.DETECTION TO ROLE INGESTION_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA SUPPLY_CHAIN_MONITOR.DETECTION TO ROLE DASHBOARD_ROLE;
GRANT SELECT ON ALL VIEWS IN SCHEMA SUPPLY_CHAIN_MONITOR.DETECTION TO ROLE DASHBOARD_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE ON ALL TABLES IN SCHEMA SUPPLY_CHAIN_MONITOR.DETECTION TO ROLE INGESTION_ROLE;
GRANT SELECT ON ALL VIEWS IN SCHEMA SUPPLY_CHAIN_MONITOR.DETECTION TO ROLE INGESTION_ROLE;
GRANT USAGE ON ALL PROCEDURES IN SCHEMA SUPPLY_CHAIN_MONITOR.DETECTION TO ROLE DASHBOARD_ROLE;
GRANT USAGE ON ALL PROCEDURES IN SCHEMA SUPPLY_CHAIN_MONITOR.DETECTION TO ROLE INGESTION_ROLE;
GRANT USAGE ON FUTURE PROCEDURES IN SCHEMA SUPPLY_CHAIN_MONITOR.DETECTION TO ROLE DASHBOARD_ROLE;
GRANT USAGE ON FUTURE PROCEDURES IN SCHEMA SUPPLY_CHAIN_MONITOR.DETECTION TO ROLE INGESTION_ROLE;
