-- GitHub-first warehouse persistence. Run after 001_schema.sql.
USE SCHEMA SUPPLY_CHAIN_MONITOR.DETECTION;

CREATE TABLE IF NOT EXISTS GITHUB_REPOSITORIES (
  REPO_NAME STRING NOT NULL,
  DEFAULT_BRANCH STRING,
  VISIBILITY STRING,
  RAW VARIANT,
  FIRST_SEEN_AT TIMESTAMP_TZ DEFAULT CURRENT_TIMESTAMP(),
  LAST_SEEN_AT TIMESTAMP_TZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS GITHUB_SCAN_RUNS (
  SCAN_ID STRING NOT NULL,
  REPO_NAME STRING NOT NULL,
  DEPENDENCY_SOURCE STRING,
  DEPENDENCY_COUNT NUMBER,
  VULNERABILITY_STATUS STRING,
  OPEN_ALERT_COUNT NUMBER,
  REPOSITORY_RISK_SCORE FLOAT,
  RAW VARIANT,
  SCANNED_AT TIMESTAMP_TZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS GITHUB_DEPENDENCY_SNAPSHOTS (
  SCAN_ID STRING NOT NULL,
  REPO_NAME STRING NOT NULL,
  PACKAGE_NAME STRING NOT NULL,
  RESOLVED_VERSION STRING,
  PURL STRING,
  SPDX_ID STRING,
  OBSERVED_AT TIMESTAMP_TZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS GITHUB_ALERT_SNAPSHOTS (
  SCAN_ID STRING NOT NULL,
  REPO_NAME STRING NOT NULL,
  ALERT_NUMBER NUMBER,
  GHSA_ID STRING,
  CLASSIFICATION STRING,
  SEVERITY STRING,
  PACKAGE_NAME STRING,
  STATE STRING,
  RAW VARIANT,
  OBSERVED_AT TIMESTAMP_TZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS GITHUB_REPOSITORY_EVENTS (
  EVENT_ID STRING NOT NULL,
  REPO_NAME STRING NOT NULL,
  EVENT_TYPE STRING NOT NULL,
  ACTOR_LOGIN STRING,
  ACTION STRING,
  MEMBER_LOGIN STRING,
  EVENT_CREATED_AT TIMESTAMP_TZ NOT NULL,
  SOURCE STRING NOT NULL,
  PAYLOAD VARIANT,
  INGESTED_AT TIMESTAMP_TZ DEFAULT CURRENT_TIMESTAMP()
)
CLUSTER BY (TO_DATE(EVENT_CREATED_AT), REPO_NAME, EVENT_TYPE);

CREATE TABLE IF NOT EXISTS GITHUB_CONTRIBUTOR_TRUST_SNAPSHOTS (
  SCORE_ID STRING NOT NULL,
  REPO_NAME STRING NOT NULL,
  ACTOR_LOGIN STRING NOT NULL,
  CONTRIBUTIONS NUMBER,
  OBSERVED_EVENTS NUMBER,
  RISK_SCORE FLOAT,
  TRUST_SCORE FLOAT,
  RISK_LEVEL STRING,
  SIGNALS VARIANT,
  WINDOW_START TIMESTAMP_TZ,
  WINDOW_END TIMESTAMP_TZ,
  SOURCE STRING,
  COMPUTED_AT TIMESTAMP_TZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS GITHUB_WEBHOOK_DELIVERIES (
  DELIVERY_ID STRING NOT NULL,
  EVENT_TYPE STRING NOT NULL,
  REPO_NAME STRING,
  PAYLOAD VARIANT,
  RECEIVED_AT TIMESTAMP_TZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE VIEW SIGNAL_GITHUB_NEW_COLLAB_FAST_PUSH AS
WITH additions AS (
  SELECT EVENT_ID, EVENT_CREATED_AT, REPO_NAME, MEMBER_LOGIN
  FROM GITHUB_REPOSITORY_EVENTS
  WHERE EVENT_TYPE='MemberEvent' AND ACTION='added' AND MEMBER_LOGIN IS NOT NULL
), pushes AS (
  SELECT EVENT_ID, EVENT_CREATED_AT, REPO_NAME, ACTOR_LOGIN
  FROM GITHUB_REPOSITORY_EVENTS
  WHERE EVENT_TYPE='PushEvent' AND ACTOR_LOGIN IS NOT NULL
), matches AS (
  SELECT p.EVENT_ID PUSH_EVENT_ID, a.EVENT_ID MEMBER_EVENT_ID,
         p.REPO_NAME, p.ACTOR_LOGIN, p.EVENT_CREATED_AT OBSERVED_AT,
         DATEDIFF('minute', a.EVENT_CREATED_AT, p.EVENT_CREATED_AT) MINUTES_TO_PUSH,
         ROW_NUMBER() OVER (PARTITION BY p.EVENT_ID ORDER BY a.EVENT_CREATED_AT DESC) RN
  FROM pushes p JOIN additions a
    ON p.REPO_NAME=a.REPO_NAME AND p.ACTOR_LOGIN=a.MEMBER_LOGIN
   AND p.EVENT_CREATED_AT BETWEEN a.EVENT_CREATED_AT AND DATEADD('hour',24,a.EVENT_CREATED_AT)
)
SELECT 'new_collaborator_fast_push' SIGNAL_NAME,
       LEAST(95,55+40*EXP(-MINUTES_TO_PUSH/180.0)) SCORE,
       REPO_NAME, ACTOR_LOGIN, OBSERVED_AT,
       'Push occurred ' || MINUTES_TO_PUSH || ' minutes after access was added.' EVIDENCE
FROM matches WHERE RN=1;

CREATE OR REPLACE VIEW SIGNAL_GITHUB_SUSPICIOUS_COMMIT_MESSAGES AS
WITH messages AS (
  SELECT e.EVENT_CREATED_AT, e.REPO_NAME, e.ACTOR_LOGIN,
         c.value:message::STRING MESSAGE
  FROM GITHUB_REPOSITORY_EVENTS e,
       LATERAL FLATTEN(INPUT=>e.PAYLOAD:commits, OUTER=>FALSE) c
  WHERE e.EVENT_TYPE='PushEvent'
), matched AS (
  SELECT *,
    REGEXP_LIKE(MESSAGE,'(preinstall|postinstall|prepare|setup\\.py|install script)','i') INSTALL_HOOK,
    REGEXP_LIKE(MESSAGE,'(eval\\s*\\(|fromcharcode|base64|atob\\s*\\(|obfuscat|encoded payload)','i') OBFUSCATION,
    REGEXP_LIKE(MESSAGE,'(token|credential|secret|\\.npmrc|aws_access_key|github_token)','i') CREDENTIAL_ACCESS,
    REGEXP_LIKE(MESSAGE,'(curl|wget|invoke-webrequest).*(sh|bash|powershell|iex)','i') DOWNLOAD_EXECUTE
  FROM messages
)
SELECT 'suspicious_commit_message' SIGNAL_NAME,
       LEAST(72,GREATEST(IFF(INSTALL_HOOK,42,0),IFF(OBFUSCATION,58,0),
              IFF(CREDENTIAL_ACCESS,54,0),IFF(DOWNLOAD_EXECUTE,70,0))) SCORE,
       REPO_NAME, ACTOR_LOGIN, EVENT_CREATED_AT OBSERVED_AT,
       'Commit metadata matched a suspicious behavior pattern; review the diff.' EVIDENCE
FROM matched WHERE INSTALL_HOOK OR OBFUSCATION OR CREDENTIAL_ACCESS OR DOWNLOAD_EXECUTE;

CREATE OR REPLACE VIEW SIGNAL_GITHUB_MULTI_REPO_BURST AS
WITH pushes AS (
  SELECT EVENT_ID, EVENT_CREATED_AT, ACTOR_LOGIN, REPO_NAME
  FROM GITHUB_REPOSITORY_EVENTS
  WHERE EVENT_TYPE='PushEvent' AND ACTOR_LOGIN IS NOT NULL
    AND EVENT_CREATED_AT >= DATEADD('day',-30,CURRENT_TIMESTAMP())
), bursts AS (
  SELECT anchor.ACTOR_LOGIN, anchor.EVENT_CREATED_AT OBSERVED_AT,
         COUNT(DISTINCT candidate.REPO_NAME) REPO_COUNT,
         MIN(candidate.REPO_NAME) REPO_NAME
  FROM pushes anchor JOIN pushes candidate
    ON anchor.ACTOR_LOGIN=candidate.ACTOR_LOGIN
   AND candidate.EVENT_CREATED_AT BETWEEN DATEADD('hour',-1,anchor.EVENT_CREATED_AT)
                                      AND anchor.EVENT_CREATED_AT
  GROUP BY anchor.ACTOR_LOGIN, anchor.EVENT_ID, anchor.EVENT_CREATED_AT
  HAVING COUNT(DISTINCT candidate.REPO_NAME) >= 10
  QUALIFY ROW_NUMBER() OVER (
    PARTITION BY anchor.ACTOR_LOGIN,DATE_TRUNC('hour',anchor.EVENT_CREATED_AT)
    ORDER BY REPO_COUNT DESC,anchor.EVENT_CREATED_AT
  )=1
)
SELECT 'multi_repo_burst' SIGNAL_NAME, LEAST(98,70+(REPO_COUNT-10)*3) SCORE,
       REPO_NAME, ACTOR_LOGIN, OBSERVED_AT,
       'Actor pushed to ' || REPO_COUNT || ' repositories within one hour.' EVIDENCE
FROM bursts;

CREATE OR REPLACE PROCEDURE REFRESH_GITHUB_CONTRIBUTOR_TRUST()
RETURNS STRING
LANGUAGE SQL
AS
$$
BEGIN
  INSERT INTO GITHUB_CONTRIBUTOR_TRUST_SNAPSHOTS (
    SCORE_ID, REPO_NAME, ACTOR_LOGIN, CONTRIBUTIONS, OBSERVED_EVENTS,
    RISK_SCORE, TRUST_SCORE, RISK_LEVEL, SIGNALS,
    WINDOW_START, WINDOW_END, SOURCE, COMPUTED_AT
  )
  WITH all_signals AS (
    SELECT * FROM SIGNAL_GITHUB_NEW_COLLAB_FAST_PUSH
    UNION ALL SELECT * FROM SIGNAL_GITHUB_SUSPICIOUS_COMMIT_MESSAGES
    UNION ALL SELECT * FROM SIGNAL_GITHUB_MULTI_REPO_BURST
  ), grouped AS (
    SELECT REPO_NAME, ACTOR_LOGIN,
           ARRAY_AGG(OBJECT_CONSTRUCT(
             'name',SIGNAL_NAME,'risk_score',SCORE,'evidence',EVIDENCE,
             'observed_at',OBSERVED_AT
           )) SIGNALS,
           100*(1-EXP(SUM(LN(GREATEST(0.001,1-SCORE/100))))) RISK_SCORE
    FROM all_signals
    WHERE OBSERVED_AT >= DATEADD('day',-30,CURRENT_TIMESTAMP())
    GROUP BY REPO_NAME,ACTOR_LOGIN
  ), scored AS (
    SELECT *, LEAST(100,ROUND(RISK_SCORE,1)) FINAL_RISK_SCORE
    FROM grouped
  )
  SELECT UUID_STRING(), REPO_NAME, ACTOR_LOGIN, 0, 0,
         FINAL_RISK_SCORE, ROUND(100-FINAL_RISK_SCORE,1),
         CASE WHEN FINAL_RISK_SCORE>=85 THEN 'critical'
              WHEN FINAL_RISK_SCORE>=65 THEN 'high'
              WHEN FINAL_RISK_SCORE>=40 THEN 'medium' ELSE 'low' END,
         SIGNALS, DATEADD('day',-30,CURRENT_TIMESTAMP()), CURRENT_TIMESTAMP(),
         'snowflake_github_events', CURRENT_TIMESTAMP()
  FROM scored;
  RETURN 'ok';
END;
$$;
